version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - chmod +x ./gradlew
      - ./gradlew clean

  build:
    commands:
      - echo Building the project...
      - ./gradlew build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes